"use client";
import {useState,useEffect} from "react";
import {CalcInput,CalcButton,CalcError,CalcShell,ResultsShell,ResultCard} from "@/components/CalcUI";
export function SleepCycleCalc(){
 const [wakeTime,setWakeTime]=useState("07:00"),[hours,setHours]=useState("8"),[latency,setLatency]=useState("15"),[result,setResult]=useState<string|null>(null),[error,setError]=useState("");
 useEffect(()=>{setResult(null);setError("");},[wakeTime,hours,latency]);
 const calculate=()=>{const match=/^(\d{2}):(\d{2})$/.exec(wakeTime),h=Number(hours),l=Number(latency);if(!match||Number(match[1])>23||Number(match[2])>59||!Number.isFinite(h)||h<=0||h>16||!Number.isFinite(l)||l<0||l>120){setError("Enter a valid time, sleep duration up to 16 hours and 0–120 minutes to fall asleep.");return;}const bed=((Number(match[1])*60+Number(match[2])-Math.round(h*60)-Math.round(l))%1440+1440)%1440;setResult(`${String(Math.floor(bed/60)).padStart(2,"0")}:${String(bed%60).padStart(2,"0")}`);};
 return <><CalcShell><p className="text-sm text-slate-600 mb-5">Work backward from your wake time and desired sleep duration. This planner cannot predict your sleep stages or guarantee refreshed waking.</p><div className="grid sm:grid-cols-2 gap-5 mb-5"><CalcInput label="I need to wake up at" value={wakeTime} onChange={setWakeTime} type="time"/><CalcInput label="Desired hours of sleep" value={hours} onChange={setHours} min={0.1} max={16}/><CalcInput label="Minutes to fall asleep" value={latency} onChange={setLatency} min={0} max={120}/></div><CalcButton onClick={calculate} label="Calculate Bedtime"/><CalcError message={error}/></CalcShell>{result&&<ResultsShell><ResultCard label="Planned bedtime" value={result} sub={`${hours} hours asleep, plus ${latency} minutes to fall asleep`}/><p className="mt-4 text-sm text-slate-600">Assumes no time awake during the night. If the clock time is later than your wake time, bedtime is on the previous day. Choose a duration appropriate for your age and circumstances.</p><a href="https://www.cdc.gov/sleep/about/index.html" className="underline text-brand-700">CDC: sleep duration recommendations</a></ResultsShell>}</>;
}
