import type {Metadata} from "next";
import Link from "next/link";
export const metadata:Metadata={title:"About ProHealthIt — Author, Methods and Corrections",description:"Who maintains ProHealthIt, how methods and sources are documented, and how to report a correction.",alternates:{canonical:"/about"},
  openGraph: { type: "website", siteName: "ProHealthIt", title: "About ProHealthIt — Author, Methods and Corrections", description: "Who maintains ProHealthIt, how methods and sources are documented, and how to report a correction.", url: "/about", images: [{url:"/og-image.png",width:1200,height:630}] },
  twitter: {card:"summary_large_image", title:"About ProHealthIt — Author, Methods and Corrections", description:"Who maintains ProHealthIt, how methods and sources are documented, and how to report a correction.", images:["/og-image.png"]},
};
export default function Page(){return <div className="max-w-[800px] mx-auto px-4 sm:px-6 py-12 space-y-6 text-slate-600 leading-relaxed">
<h1 className="text-3xl font-bold text-slate-900">About ProHealthIt</h1><p>ProHealthIt is an independent educational health information project maintained by Ash K, based in Dehradun, India. His background is technology and independent research; he is not a doctor or licensed medical professional.</p>
<h2 className="text-xl font-bold text-slate-900">Methods and sources</h2><p>Each tool should explain what it calculates, the reference used, its units and its limits. A published equation or questionnaire does not mean a particular website implementation is clinically validated. No independent clinical review is claimed unless a named qualified reviewer and the actual review scope are documented.</p>
<p>Recent corrections include unit conversion, lean-mass arithmetic, CDC/WHO growth data, EPDS scoring and overnight sleep arithmetic. Unsupported custom risk scores and personalized outputs have been withdrawn or replaced with clearly labelled educational guidance. The previous blanket claims that all methods were exact and every claim came only from primary sources have been removed.</p>
<h2 className="text-xl font-bold text-slate-900">Editorial standards</h2><ol className="list-decimal pl-6 space-y-2"><li>Identify the exact source, applicable population and version.</li><li>Check consequential calculations with independent reference cases, including units and boundaries.</li><li>Keep instructions, results, articles and metadata consistent.</li><li>Explain uncertainty and seek qualified review where clinical interpretation is needed.</li></ol><p>These are maintenance standards, not a claim that every legacy article has completed a clinical review. Updated dates indicate a content or method change, not medical approval.</p>
<h2 className="text-xl font-bold text-slate-900">Privacy and independence</h2><p>Calculator values are handled locally by the application. Usage measurement and advertising use third-party services; see the <Link href="/privacy" className="underline text-brand-700">privacy policy</Link>. Advertising does not constitute medical endorsement.</p>
<h2 className="text-xl font-bold text-slate-900">Contact and corrections</h2><p>Report the page URL and the issue to <a className="underline text-brand-700" href="mailto:hello@prohealthit.com">hello@prohealthit.com</a>. Avoid emailing sensitive health details. Important corrections should state what changed and when.</p><p>This resource does not replace professional medical advice, diagnosis or treatment. <Link href="/disclaimer" className="underline text-brand-700">Read the medical disclaimer</Link>.</p>
</div>;}
