"use client";
import {useState,useEffect} from "react";
import {parseLocalDate,calendarDays,estimatedOvulation} from "@/lib/health-math";
import {CalcInput,CalcButton,CalcShell,CalcError,ResultsShell,ResultCard} from "@/components/CalcUI";
const fmt=(d:Date)=>d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
export function OvulationCalc(){
 const [lmpDate,setLmpDate]=useState(""),[cycleLen,setCycleLen]=useState("28"),[error,setError]=useState(""),[result,setResult]=useState<ReturnType<typeof estimatedOvulation>|null>(null);
 useEffect(()=>{setResult(null);setError("");},[lmpDate,cycleLen]);
 const calculate=()=>{try{setError("");const date=parseLocalDate(lmpDate);if(calendarDays(date,new Date())<0)throw new Error("Use a period date on or before today.");setResult(estimatedOvulation(date,Number(cycleLen)));}catch(e){setResult(null);setError((e as Error).message);}};
 return <><CalcShell><p className="text-sm text-slate-600 mb-5">A calendar estimate for cycle lengths of 21–45 days. It assumes ovulation on cycle day (cycle length − 14), counting the first period day as day 1. Actual timing can differ, including in regular cycles. Do not use these dates for contraception.</p><div className="grid sm:grid-cols-2 gap-5 mb-5"><CalcInput label="First day of last period" value={lmpDate} onChange={setLmpDate} type="date"/><CalcInput label="Average cycle length (days)" value={cycleLen} onChange={setCycleLen} min={21} max={45} step={1}/></div><CalcButton onClick={calculate} label="Estimate Fertile Window"/><CalcError message={error}/></CalcShell>{result&&<ResultsShell><div className="grid sm:grid-cols-2 gap-4"><ResultCard label="Estimated ovulation" value={fmt(result.ovulation)}/><ResultCard label="Estimated six-day window" value={`${fmt(result.windowStart)} – ${fmt(result.windowEnd)}`} sub="Five days before estimated ovulation, plus that day"/><ResultCard label="Estimated next period" value={fmt(result.nextPeriod)}/></div><div className="grid grid-cols-3 sm:grid-cols-6 gap-2 mt-5" aria-label="Six estimated fertile days">{Array.from({length:6},(_,i)=>{const d=new Date(result.windowStart);d.setDate(d.getDate()+i);return <div key={i} className="rounded-lg bg-brand-50 p-2 text-center text-sm">{d.toLocaleDateString("en-US",{month:"short",day:"numeric"})}</div>;})}</div><p className="text-sm mt-4 text-slate-600">These are estimated dates, not confirmation of ovulation or safe days. Irregular cycles and some medical circumstances make a calendar model less useful.</p><a href="https://www.asrm.org/practice-guidance/practice-committee-documents/optimizing-natural-fertility-a-committee-opinion-2021/" className="underline text-brand-700">ASRM: fertile window and limitations of calendar methods</a></ResultsShell>}</>;
}
