"use client";
import {useState,useEffect} from "react";
import {hcgChange} from "@/lib/health-math";
import {CalcInput,CalcButton,CalcShell,CalcError,ResultsShell,ResultCard} from "@/components/CalcUI";
export function HcgCalc(){
 const [first,setFirst]=useState(""),[second,setSecond]=useState(""),[hours,setHours]=useState("48"),[error,setError]=useState(""),[result,setResult]=useState<ReturnType<typeof hcgChange>|null>(null);
 useEffect(()=>{setResult(null);setError("");},[first,second,hours]);
 const calculate=()=>{try{setError("");setResult(hcgChange(Number(first),Number(second),Number(hours)));}catch(e){setResult(null);setError((e as Error).message);}};
 return <><CalcShell><p className="text-sm text-slate-600 mb-5">Enter results in chronological order and the actual elapsed hours between blood draws. The result describes arithmetic change; it does not determine pregnancy location or viability.</p><div className="grid sm:grid-cols-2 gap-5 mb-5"><CalcInput label="First hCG value (mIU/mL)" value={first} onChange={setFirst}/><CalcInput label="Second hCG value (mIU/mL)" value={second} onChange={setSecond}/><CalcInput label="Hours between blood draws" value={hours} onChange={setHours}/></div><CalcButton onClick={calculate} label="Calculate hCG Change"/><CalcError message={error}/></CalcShell>{result&&<ResultsShell><div className="grid sm:grid-cols-2 gap-4"><ResultCard label="Observed change" value={`${result.increase.toFixed(1)}%`} sub={result.trend}/><ResultCard label="Elapsed time" value={`${result.hours} hours`}/><ResultCard label="Calculated doubling time" value={result.doublingTime===null?"Not applicable":`${result.doublingTime.toFixed(1)} hours`} sub="Defined only for an increase"/>{result.halvingTime!==null&&<ResultCard label="Calculated halving time" value={`${result.halvingTime.toFixed(1)} hours`} sub="Describes a decrease; not a diagnosis"/>}</div><p className="mt-4 text-sm text-slate-600">The calculation describes the exponential rate between these two values; it does not predict that the rate will continue. A fast rise cannot rule out ectopic pregnancy, and a slow rise cannot establish a diagnosis. Follow the testing and assessment plan given by your care team.</p><a href="https://www.nice.org.uk/guidance/NG126/chapter/diagnosis-of-viable-intrauterine-pregnancy-and-of-tubal-ectopic-pregnancy" className="underline text-brand-700">NICE NG126: how serial hCG is used when pregnancy location is unknown</a></ResultsShell>}</>;
}
