"use client";
import { useState, useEffect } from "react";
import { CalcInput, CalcButton, CalcShell, ResultsShell, ResultCard, CalcError } from "@/components/CalcUI";
export function ThyroidCalc(){
 const [tsh,setTsh]=useState(""),[tshMin,setTshMin]=useState(""),[tshMax,setTshMax]=useState(""),[ft4,setFt4]=useState(""),[ft4Min,setFt4Min]=useState(""),[ft4Max,setFt4Max]=useState("");
 const [result,setResult]=useState<{tsh:string;ft4:string}|null>(null),[error,setError]=useState("");
 useEffect(()=>setResult(null),[tsh,tshMin,tshMax,ft4,ft4Min,ft4Max]);
 const calculate=()=>{setError("");const compare=(v:string,lo:string,hi:string)=>{const x=Number(v),l=Number(lo),h=Number(hi);if(!v||!lo||!hi||![x,l,h].every(Number.isFinite)||x<0||l<0||h<=l)throw new Error("Enter the value and both limits from the same lab report, with a lower limit below the upper limit.");return x<l?"Below lab range":x>h?"Above lab range":"Within lab range";};try{const t=compare(tsh,tshMin,tshMax);const f=ft4||ft4Min||ft4Max?compare(ft4,ft4Min,ft4Max):"Not provided";setResult({tsh:t,ft4:f});}catch(e){setResult(null);setError((e as Error).message);}};
 return <><CalcShell><p className="text-sm text-slate-600 mb-5">Compare values with the reference intervals printed on your own lab report. Use the same units throughout each row. Pregnancy needs appropriate lab/trimester ranges and clinical interpretation; this tool does not diagnose thyroid disease or select treatment.</p><div className="grid sm:grid-cols-3 gap-5 mb-5"><CalcInput label="TSH value (lab units)" value={tsh} onChange={setTsh} min={0}/><CalcInput label="TSH lower reference limit" value={tshMin} onChange={setTshMin} min={0}/><CalcInput label="TSH upper reference limit" value={tshMax} onChange={setTshMax}/><CalcInput label="Free T4 value (optional, lab units)" value={ft4} onChange={setFt4} min={0}/><CalcInput label="Free T4 lower limit (optional)" value={ft4Min} onChange={setFt4Min} min={0}/><CalcInput label="Free T4 upper limit (optional)" value={ft4Max} onChange={setFt4Max}/></div><CalcButton onClick={calculate} label="Compare With Lab Ranges"/><CalcError message={error}/></CalcShell>{result&&<ResultsShell><div className="grid sm:grid-cols-2 gap-4"><ResultCard label="TSH" value={result.tsh}/><ResultCard label="Free T4" value={result.ft4}/></div><p className="text-sm mt-4">Being within a range is not proof of normal thyroid function. Discordant TSH and free T4 results, symptoms, medication and pregnancy need clinician review.</p><a className="underline text-brand-700" href="https://www.thyroid.org/thyroid-function-tests/">American Thyroid Association: thyroid function tests</a></ResultsShell>}</>;
}
