import type {Metadata} from "next";
export const metadata:Metadata={title:"Privacy Policy",description:"Calculator inputs, usage analytics, advertising and privacy choices on ProHealthIt.",alternates:{canonical:"/privacy"},
  openGraph: { type: "website", siteName: "ProHealthIt", title: "Privacy Policy", description: "Calculator inputs, usage analytics, advertising and privacy choices on ProHealthIt.", url: "/privacy", images: [{url:"/og-image.png",width:1200,height:630}] },
  twitter: {card:"summary_large_image", title:"Privacy Policy", description:"Calculator inputs, usage analytics, advertising and privacy choices on ProHealthIt.", images:["/og-image.png"]},
};
export default function Page(){return <div className="max-w-[760px] mx-auto px-4 sm:px-6 py-12 space-y-5 text-slate-600 leading-relaxed">
<h1 className="text-3xl font-bold text-slate-900">Privacy Policy</h1><p>Updated 2 October 2026.</p>
<h2 className="text-xl font-bold text-slate-900">Calculator inputs</h2><p>The application processes calculator values in your browser and does not intentionally send your health inputs or results to its analytics events. No account is required. This is separate from usage data, cookies and request data processed by hosting and third parties. Please avoid including sensitive health information in URLs or contact messages.</p>
<h2 className="text-xl font-bold text-slate-900">Usage measurement</h2><p>The site uses Google Analytics 4, Vercel Analytics and Vercel Speed Insights. These services may process page visits, device/browser information, approximate location, referral information, identifiers and performance measurements according to their settings and policies. Calculator start/completion events contain only an event name and tool identifier, not entered values or derived scores. We do not describe all usage data as anonymous or as non-personal.</p>
<h2 className="text-xl font-bold text-slate-900">Advertising</h2><p>Google AdSense is used for advertising. Google and its partners may use cookies and other identifiers for ad delivery, measurement and personalization according to their policies and applicable choices. Advertising scripts are separate from local calculator code. Review <a href="https://policies.google.com/technologies/partner-sites" className="underline">Google’s information about partner sites</a> and <a href="https://myadcenter.google.com/" className="underline">Google ad choices</a>.</p>
<h2 className="text-xl font-bold text-slate-900">Cookies and choices</h2><p>Google Analytics uses cookies. You can control cookies in your browser and use available analytics/ad preference tools. Where applicable, choices provided by the site’s consent platform govern third-party processing. Browser controls may affect site features.</p>
<h2 className="text-xl font-bold text-slate-900">Hosting and external links</h2><p>Vercel hosts the site and may process request/log information such as IP addresses. External reference websites have their own policies. See <a href="https://vercel.com/legal/privacy-policy" className="underline">Vercel’s privacy policy</a> and <a href="https://policies.google.com/privacy" className="underline">Google’s privacy policy</a>.</p>
<h2 className="text-xl font-bold text-slate-900">Contact</h2><p>Contact <a href="mailto:hello@prohealthit.com" className="underline">hello@prohealthit.com</a> for privacy questions. Email itself can contain personal information; do not send unnecessary health details. This policy describes the implementation and does not promise that third parties collect no data.</p>
</div>;}
