"use client";
import { useState, useEffect } from "react";
import { CalcInput, CalcSelect, CalcButton, CalcShell, ResultsShell, ResultCard, StatusBadge, UnitToggle, CalcError } from "@/components/CalcUI";
import { teenBMI } from "@/lib/bmi-math";
export function BmiTeensCalc(){
 const [unit,setUnit]=useState("metric"),[years,setYears]=useState(""),[months,setMonths]=useState("0"),[gender,setGender]=useState("male"),[weight,setWeight]=useState(""),[height,setHeight]=useState("");
 const [result,setResult]=useState<ReturnType<typeof teenBMI>|null>(null),[error,setError]=useState("");
  useEffect(()=>{setResult(null);},[unit,years,months,gender,weight,height]);
 const calculate=()=>{try{setError("");if(!Number.isInteger(Number(years))||!Number.isInteger(Number(months)))throw new Error("Use completed whole years and additional months.");setResult(teenBMI(Number(years)*12+Number(months),Number(weight),Number(height),gender,unit==="imperial"));}catch(e){setResult(null);setError((e as Error).message);}};
 return <><CalcShell><UnitToggle value={unit} onChange={v=>{setUnit(v);setWeight("");setHeight("");}}/><div className="grid sm:grid-cols-2 gap-5 mb-5"><CalcInput label="Completed years (2–19)" value={years} onChange={setYears} min={2} max={19} step={1}/><CalcInput label="Additional completed months (0–11)" value={months} onChange={setMonths} min={0} max={11} step={1}/><CalcSelect label="Sex used by CDC chart" value={gender} onChange={setGender} options={[{value:"male",label:"Male"},{value:"female",label:"Female"}]}/><CalcInput label={`Weight (${unit==="metric"?"kg":"lb"})`} value={weight} onChange={setWeight}/><CalcInput label={`Height (${unit==="metric"?"cm":"in"})`} value={height} onChange={setHeight}/></div><CalcButton onClick={calculate} label="Calculate BMI-for-age"/><CalcError message={error}/></CalcShell>
 {result&&<ResultsShell><StatusBadge status={result.status} text={result.category}/><div className="grid sm:grid-cols-3 gap-4"><ResultCard label="BMI" value={result.bmi.toFixed(2)}/><ResultCard label="CDC percentile" value={result.extreme?"Not estimated in this range":`${result.percentile.toFixed(2)}th`} highlight/><ResultCard label="Reference" value="CDC 2000 LMS" sub="Sex and completed-month age"/></div><p className="text-sm mt-4 text-slate-600">This is a screening measure, not a diagnosis. Numeric percentiles are withheld below the 3rd or above the 95th percentile. CDC permits either standard or extended charts from the 95th through 97th percentiles and recommends the extended chart above the 97th; this calculator does not implement the extended method. Interpret growth over time with a pediatric clinician. Categories use the unrounded percentile.</p><a className="underline text-brand-700" href="https://www.cdc.gov/growthcharts/extended-bmi-data-files.htm">CDC extended BMI-for-age charts</a></ResultsShell>}</>;
}
